# Generated by Django 2.1.12 on 2020-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('lux', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
